// Command gentables turns the Rust Unicode dump into the fork's tables.
//
// The dump (internal/unicodecase/testdata/rust-unicode.json, produced by
// oracle/harness/src/casegen.rs) is the engine's own answer for every Unicode
// scalar. Generating internal/unicodecase from it is what makes the fork's
// string builtins Unicode-identical to the engine by construction, rather than
// identical-looking because both call something named "to upper".
//
//	go run ./cmd/gentables        # rewrite ../internal/unicodecase/tables.go
//
// This lives in the test-only oracle module: the engine module ships the
// generated table, not the generator.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"runtime"
	"sort"
)

type dump struct {
	SchemaVersion int          `json:"schema_version"`
	Rustc         string       `json:"rustc"`
	ToUpper       []mappingRaw `json:"to_uppercase"`
	ToLower       []mappingRaw `json:"to_lowercase"`
	Lowercase     [][2]rune    `json:"lowercase"`
	Uppercase     [][2]rune    `json:"uppercase"`
	Alphabetic    [][2]rune    `json:"alphabetic"`
	Numeric       [][2]rune    `json:"numeric"`
	Whitespace    [][2]rune    `json:"whitespace"`
	Cased         [][2]rune    `json:"cased"`
	CaseIgnorable [][2]rune    `json:"case_ignorable"`
	Samples       [][6]string  `json:"samples"`
}

// mappingRaw is one [scalar, mapping] pair.
type mappingRaw struct {
	Rune rune
	To   string
}

func (m *mappingRaw) UnmarshalJSON(data []byte) error {
	var pair []json.RawMessage
	if err := json.Unmarshal(data, &pair); err != nil {
		return err
	}
	if len(pair) != 2 {
		return fmt.Errorf("mapping entry has %d fields, want 2", len(pair))
	}
	if err := json.Unmarshal(pair[0], &m.Rune); err != nil {
		return err
	}
	return json.Unmarshal(pair[1], &m.To)
}

const schemaVersion = 1

func main() {
	// Derived from this file's own location rather than from the oracle
	// package: the tables it writes are what makes the engine module compile,
	// so the generator must not import anything that depends on them.
	_, self, _, ok := runtime.Caller(0)
	if !ok {
		fail(fmt.Errorf("cannot determine source location"))
	}
	engine := filepath.Dir(filepath.Dir(filepath.Dir(filepath.Dir(self))))
	dumpPath := filepath.Join(engine, "internal", "unicodecase", "testdata", "rust-unicode.json")
	raw, err := os.ReadFile(dumpPath)
	if err != nil {
		fail(err)
	}
	var d dump
	if err := json.Unmarshal(raw, &d); err != nil {
		fail(fmt.Errorf("%s: %w", dumpPath, err))
	}
	if d.SchemaVersion != schemaVersion {
		fail(fmt.Errorf("%s: schema_version %d, want %d", dumpPath, d.SchemaVersion, schemaVersion))
	}

	var buf bytes.Buffer
	fmt.Fprintf(&buf, `// Code generated by oracle/cmd/gentables from
// internal/unicodecase/testdata/rust-unicode.json. DO NOT EDIT.
//
// Source of truth: %s, whose Unicode tables are the ones BAML's engine build
// uses. Regenerate with:
//
//	cd oracle/harness && cargo build --release --bin mj-casegen
//	MJ_RUSTC_VERSION="$(rustc --version)" ./oracle/harness/target/release/mj-casegen \
//	    > internal/unicodecase/testdata/rust-unicode.json
//	cd oracle && go run ./cmd/gentables

package unicodecase

// rustcVersion is the toolchain the tables were dumped from. Character
// properties and case mappings track the Rust release's Unicode version, so a
// mismatch here is the first thing to check when a casing row diverges.
const rustcVersion = %q
`, d.Rustc, d.Rustc)

	writeMappings(&buf, "upperMap", "str::to_uppercase, tabulated per scalar", d.ToUpper)
	writeMappings(&buf, "lowerMap", "str::to_lowercase, tabulated per scalar (the final-sigma\n// rule is context sensitive and lives in ToLower, not here)", d.ToLower)

	writeRanges(&buf, "lowercaseRanges", "char::is_lowercase (the Unicode Lowercase property, which is wider\n// than Go's unicode.IsLower)", d.Lowercase)
	writeRanges(&buf, "uppercaseRanges", "char::is_uppercase", d.Uppercase)
	writeRanges(&buf, "alphabeticRanges", "char::is_alphabetic (the Alphabetic property: Go's unicode.IsLetter\n// is category L only and answers differently for ~11k scalars)", d.Alphabetic)
	writeRanges(&buf, "numericRanges", "char::is_numeric", d.Numeric)
	writeRanges(&buf, "whitespaceRanges", "char::is_whitespace", d.Whitespace)
	writeRanges(&buf, "casedRanges", "the Unicode Cased property, used by the final-sigma rule", d.Cased)
	writeRanges(&buf, "caseIgnorableRanges", "the Unicode Case_Ignorable property, used by the final-sigma rule", d.CaseIgnorable)

	src, err := format.Source(buf.Bytes())
	if err != nil {
		fail(fmt.Errorf("generated source does not parse: %w", err))
	}
	out := filepath.Join(engine, "internal", "unicodecase", "tables.go")
	if err := os.WriteFile(out, src, 0o644); err != nil {
		fail(err)
	}
	fmt.Fprintf(os.Stderr, "wrote %s: %d upper, %d lower mappings; %d property ranges\n",
		out, len(d.ToUpper), len(d.ToLower),
		len(d.Lowercase)+len(d.Uppercase)+len(d.Alphabetic)+len(d.Numeric)+
			len(d.Whitespace)+len(d.Cased)+len(d.CaseIgnorable))
}

func writeMappings(buf *bytes.Buffer, name, doc string, entries []mappingRaw) {
	sorted := append([]mappingRaw(nil), entries...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Rune < sorted[j].Rune })
	fmt.Fprintf(buf, "\n// %s is %s.\nvar %s = map[rune]string{\n", name, doc, name)
	for _, e := range sorted {
		fmt.Fprintf(buf, "\t%q: %q,\n", e.Rune, e.To)
	}
	buf.WriteString("}\n")
}

func writeRanges(buf *bytes.Buffer, name, doc string, ranges [][2]rune) {
	fmt.Fprintf(buf, "\n// %s is %s.\nvar %s = []runeRange{\n", name, doc, name)
	for _, r := range ranges {
		fmt.Fprintf(buf, "\t{%q, %q},\n", r[0], r[1])
	}
	buf.WriteString("}\n")
}

func fail(err error) {
	fmt.Fprintf(os.Stderr, "gentables: %v\n", err)
	os.Exit(1)
}
